/*----------------------------------------------------------
MASV: N17DCAT031
HO TEN: VÕ PHI HÙNG
LAB: 03
NGAY: 18/09/2020
----------------------------------------------------------*/
USE QLSV
GO
CREATE PROC SP_INS_NHANVIEN (
	@MANV VARCHAR(20) ,
	@HOTEN NVARCHAR(100) ,
	@EMAIL VARCHAR(20) ,
	@LUONG INT,
	@TENDN NVARCHAR(100), 
	@MATKHAU VARCHAR(32)  )
AS
BEGIN
	DECLARE @SALARY VARBINARY (256), @MK VARBINARY (256)
	OPEN SYMMETRIC KEY AES_256_ENCRYPT DECRYPTION BY CERTIFICATE MY_ENCRYPT_CERT  
	SET @SALARY = EncryptByKey(Key_GUID('AES_256_ENCRYPT'),CONVERT(VARCHAR(32),@LUONG))
	CLOSE SYMMETRIC KEY AES_256_ENCRYPT
	SET @MK = HASHBYTES('SHA1',@MATKHAU)
	INSERT INTO NHANVIEN(MANV,HOTEN,EMAIL,LUONG,TENDN,MATKHAU)
	VALUES(@MANV,@HOTEN,@EMAIL,@SALARY,@TENDN,@MK)
END