/*----------------------------------------------------------
MASV: N17DCAT031
HO TEN: VÕ PHI HÙNG
LAB: 03
NGAY: 18/09/2020
----------------------------------------------------------*/
CREATE PROC SP_SEL_NHANVIEN
AS
BEGIN
	OPEN SYMMETRIC KEY AES_256_ENCRYPT DECRYPTION BY CERTIFICATE MY_ENCRYPT_CERT  
	SELECT MANV, HOTEN, EMAIL, CONVERT(VARCHAR(32), DecryptByKey(NHANVIEN.LUONG)) AS LUONGCB
	FROM NHANVIEN
	CLOSE SYMMETRIC KEY AES_256_ENCRYPT
END

--EXEC SP_SEL_NHANVIEN